apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    app: poi
  namespace: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "tripinsights-keyvault"
      containers:
        - name: poi
          image: registryzlt8225.azurecr.io/tripinsights/poi:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: secrets-store-inline 
            mountPath: "/secrets"
            readOnly: true  
          
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  labels:
    run: poi
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: poi
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
