apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  labels:
    app: userprofile
  namespace: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userprofile
  volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "tripinsights-keyvault"
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: registryzlt8225.azurecr.io/tripinsights/userprofile:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
          - name: secrets-store-inline 
            mountPath: "/secrets"
            readOnly: true  
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  labels:
    app: userprofile
  namespace: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: userprofile
