apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tripinsights-keyvault
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "7324436e-2a16-48d0-af32-851f943a358b"
    keyvaultName: "tripinsightskv003"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: SQLSERVER
          objectAlias: SQL_SERVER
          objectType: secret              
          objectVersion: ""
        - |
          objectName: SQLDBNAME
          objectAlias: SQL_DBNAME
          objectType: secret              
          objectVersion: ""
        - |
          objectName: SQLUSER
          objectAlias: SQL_USER
          objectType: secret              
          objectVersion: ""
        - |
          objectName: SQLPASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret              
          objectVersion: ""
    tenantId: "6eb3875c-22ba-436b-afaa-7b1bcec101f5"
